### PR TITLE
Add EXTEND-QUEUE-P

### LINKED ISSUE #3: static queue size option
It would be a useful feature to disable adjustment when constructing a queue, and signal a condition if the queue is full when enqueuing, as it could help detect cycles in an event system before your heap is exhausted, as well as give insight into performance penalties.

### PR DESCRIPTION
**Pull request by phoe**
Fixes #3

@mfiano Please review - this is the solution for DFPQ, if it looks OK to you, then I'll copy it to DFSPQ and update the documentation.

### CODE REVIEW

**Comment by mfiano** [comment]
Looks good to me at glance.

**Comment by phoe** [comment]
OK. Care to pull the branch someday and give it a try locally?

**Comment by mfiano** [comment]
I can do that tomorrow.

**Comment by phoe** [comment]
Pushed a new commit that contains updates to both queues, as well as a README update.

Fixes #3

**Pull request merged**
